/*-------------------------------------------------------------------------
 *
 * Imagineer - TTRPG Campaign Intelligence Platform
 *
 * Copyright (c) 2025 - 2026
 * This software is released under The MIT License
 *
 *-------------------------------------------------------------------------
 */

-- Migration 005: Entity Log and Enrichment
--
-- This migration:
-- 1. Creates entity_log for chronological event history per entity
-- 2. Adds enrichment columns to content_analysis_items
-- 3. Adds enrichment tracking columns to content_analysis_jobs

-- ============================================
-- Entity Log Table
-- Chronological event history per entity
-- ============================================
CREATE TABLE entity_log (
    id           BIGSERIAL PRIMARY KEY,
    entity_id    BIGINT NOT NULL
                 REFERENCES entities(id) ON DELETE CASCADE,
    campaign_id  BIGINT NOT NULL
                 REFERENCES campaigns(id) ON DELETE CASCADE,
    chapter_id   BIGINT REFERENCES chapters(id)
                 ON DELETE SET NULL,
    session_id   BIGINT REFERENCES sessions(id)
                 ON DELETE SET NULL,
    source_table TEXT,
    source_id    BIGINT,
    content      TEXT NOT NULL,
    occurred_at  TEXT,
    sort_order   INT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE entity_log IS 'Chronological event history entries for campaign entities';
COMMENT ON COLUMN entity_log.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN entity_log.entity_id IS 'Entity this log entry belongs to';
COMMENT ON COLUMN entity_log.campaign_id IS 'Campaign this log entry belongs to';
COMMENT ON COLUMN entity_log.chapter_id IS 'Chapter where this event occurred (optional)';
COMMENT ON COLUMN entity_log.session_id IS 'Session where this event occurred (optional)';
COMMENT ON COLUMN entity_log.source_table IS 'Source table that generated this log entry (e.g., from enrichment)';
COMMENT ON COLUMN entity_log.source_id IS 'Row ID in the source table';
COMMENT ON COLUMN entity_log.content IS 'Description of the event or log entry';
COMMENT ON COLUMN entity_log.occurred_at IS 'When the event occurred in the game timeline (free-text)';
COMMENT ON COLUMN entity_log.sort_order IS 'Manual ordering within the entity timeline';
COMMENT ON COLUMN entity_log.created_at IS 'Timestamp when the log entry was created';

CREATE INDEX idx_entity_log_entity_sort
    ON entity_log(entity_id, sort_order);
CREATE INDEX idx_entity_log_campaign_entity
    ON entity_log(campaign_id, entity_id);

-- ============================================
-- Alter content_analysis_items for enrichment
-- ============================================
ALTER TABLE content_analysis_items
    ADD COLUMN suggested_content JSONB,
    ADD COLUMN phase TEXT NOT NULL DEFAULT 'identification';

COMMENT ON COLUMN content_analysis_items.suggested_content IS 'Structured JSON payload for enrichment suggestions (description updates, log entries, relationships)';
COMMENT ON COLUMN content_analysis_items.phase IS 'Analysis phase: identification (Phase 1 text analysis) or enrichment (Phase 2 LLM suggestions)';

-- ============================================
-- Alter content_analysis_jobs for enrichment tracking
-- ============================================
ALTER TABLE content_analysis_jobs
    ADD COLUMN enrichment_total INT NOT NULL DEFAULT 0,
    ADD COLUMN enrichment_resolved INT NOT NULL DEFAULT 0;

COMMENT ON COLUMN content_analysis_jobs.enrichment_total IS 'Total number of enrichment suggestions generated by LLM';
COMMENT ON COLUMN content_analysis_jobs.enrichment_resolved IS 'Number of enrichment suggestions that have been reviewed';

-- ============================================
-- Record migration
-- ============================================
INSERT INTO schema_migrations (version) VALUES ('005_entity_log_and_enrichment');
